# to create this env with this .yml: conda env create -f environment.yml
name: pycones22_UQ_XAI
channels:
- conda-forge
dependencies:
- python=3.9.1
- jupyter=1.0.0
- jupyter_contrib_nbextensions=0.5.1
- matplotlib=3.4.3
- numpy=1.19.5
- pandas=1.3.2
- pip=21.3.1
- scikit-learn=1.1.1
- seaborn=0.11.2
- python-graphviz==0.19.1
- xgboost=1.4.2
- shap=0.41.0
- dice-ml=0.8 
- emoji=1.6.1



