# to create this env with this .yml: conda env create -f environment.yml
name: intro_UQ_XAI
channels:
- conda-forge
dependencies:
- python=3.9.1
- jupyter
- jupyter_contrib_nbextensions
- matplotlib
- numpy
- pandas
- pip
- scikit-learn
- seaborn
- xgboost
- dice-ml
- emoji

